-- ============================================================================
-- repo_scopes — first-class scope table (replaces access_points.config.scope)
-- ============================================================================
-- Why
--   Scope was previously embedded as JSONB inside access_points.config. That
--   coupling forced a single access_point to "be" a single scope, which made
--   "1 repo, N scopes, all keys belong to the same repo" impossible to model
--   without overloading access_points further. This migration extracts scope
--   into its own table.
--
--   See docs/design/access-point-redesign-2026-05-02.md (sections 5.1, 5.3).
--
-- What it does
--   1. Creates repo_scopes (with auto-generated per-scope access_key).
--   2. Adds the partial UNIQUE for "exactly one root scope per project".
--   3. Adds the trigger/function for auto-creating cli + agent connectors
--      lives in the NEXT migration (20260502000100_connectors_table.sql) so
--      that this file is independently re-runnable in any order against an
--      empty DB.
--
-- Idempotency
--   CREATE TABLE IF NOT EXISTS + CREATE INDEX IF NOT EXISTS + DO blocks
--   guarding the policy. Re-running yields the same final state.
-- ============================================================================

BEGIN;

-- ── Table ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.repo_scopes (
    id            TEXT        PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
    project_id    TEXT        NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,

    -- Display name, e.g. "Documentation", "Source code". Editable.
    name          TEXT        NOT NULL,

    -- Canonical path. Empty string '' = root scope. No leading/trailing /.
    -- Same canonicalization as mut_scope_state.scope_path
    -- (cf. supabase/migrations/20260416100000_scope_path_canonical.sql).
    path          TEXT        NOT NULL,

    -- Subtree exclusions; entries are path-relative to `path`.
    exclude       JSONB       NOT NULL DEFAULT '[]'::JSONB,

    -- 'r' (read-only) or 'rw' (read-write). The mut library enforces this in
    -- handle_push by rejecting the request when mode='r' (cf. mut/server/handlers.py:93).
    mode          TEXT        NOT NULL DEFAULT 'rw'
        CHECK (mode IN ('r', 'rw')),

    -- Auto-created project-root scope. Never deletable (enforced by service layer).
    is_root       BOOLEAN     NOT NULL DEFAULT FALSE,

    -- Per-scope access key. The mut credential for this scope.
    -- Format: cli_<urlsafe-32>  matches existing access_points.access_key
    -- so old `mut connect` clients keep working post-migration.
    -- Generated by the service layer on INSERT (Python secrets.token_urlsafe(32)).
    access_key            TEXT        NOT NULL UNIQUE,
    access_key_revoked_at TIMESTAMPTZ,

    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- One scope row per (project, path).
    UNIQUE (project_id, path)
);

-- Exactly one root scope per project. PostgreSQL partial UNIQUE.
CREATE UNIQUE INDEX IF NOT EXISTS idx_repo_scopes_one_root_per_project
    ON public.repo_scopes (project_id) WHERE is_root = TRUE;

CREATE INDEX IF NOT EXISTS idx_repo_scopes_project
    ON public.repo_scopes (project_id);

-- Hot path for mut auth: "given an access_key, find the scope".
CREATE INDEX IF NOT EXISTS idx_repo_scopes_access_key_active
    ON public.repo_scopes (access_key) WHERE access_key_revoked_at IS NULL;

-- ── updated_at auto-bump ──────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public._repo_scopes_bump_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_repo_scopes_updated_at ON public.repo_scopes;
CREATE TRIGGER trg_repo_scopes_updated_at
    BEFORE UPDATE ON public.repo_scopes
    FOR EACH ROW
    EXECUTE FUNCTION public._repo_scopes_bump_updated_at();

-- ── Path canonicalization guard (matches scope_path_canonical migration) ──
-- Reject any path that starts/ends with /, or contains // (double slash).
-- The empty string '' (root scope) is allowed.
ALTER TABLE public.repo_scopes
    DROP CONSTRAINT IF EXISTS repo_scopes_path_canonical;
ALTER TABLE public.repo_scopes
    ADD CONSTRAINT repo_scopes_path_canonical CHECK (
        path = '' OR (
            path NOT LIKE '/%' AND
            path NOT LIKE '%/' AND
            path NOT LIKE '%//%'
        )
    );

-- ── RLS ───────────────────────────────────────────────────────────────────
ALTER TABLE public.repo_scopes ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'repo_scopes'
          AND policyname = 'repo_scopes_service_role_all'
    ) THEN
        CREATE POLICY "repo_scopes_service_role_all"
            ON public.repo_scopes
            FOR ALL TO service_role
            USING (true) WITH CHECK (true);
    END IF;
END $$;

COMMIT;
