#!/bin/sh
set -eu
# JWTs are generated by Supabase and only contain URL-safe token characters.
# Reject template injection rather than evaluating environment values as shell.
case "$ANON_KEY:$SERVICE_ROLE_KEY" in *[!A-Za-z0-9_.:-]*) exit 1 ;; esac
sed -e "s|__ANON_KEY__|$ANON_KEY|g" -e "s|__SERVICE_ROLE_KEY__|$SERVICE_ROLE_KEY|g" \
  /var/lib/kong/kong.template.yml > /tmp/kong.yml
export KONG_DECLARATIVE_CONFIG=/tmp/kong.yml
exec /docker-entrypoint.sh kong docker-start
