-- ============================================================================
-- OAuth state CSRF protection (security: M-2)
-- ============================================================================
-- Purpose
--   Persist server-side OAuth `state` nonces so the callback can verify the
--   redirect originated from this server, was issued to the same user, and
--   has not expired or been replayed.
--
-- Why
--   Before this migration, the OAuth `state` parameter was generated by the
--   service but never stored. The callback handler accepted any callback for
--   the authenticated user, which means an attacker who tricks a victim into
--   visiting an attacker-controlled OAuth callback URL could attach the
--   victim's account to the attacker's third-party identity.
--
-- Idempotency
--   `CREATE TABLE IF NOT EXISTS` + `CREATE INDEX IF NOT EXISTS` + DO blocks
--   guarding policy creation. Re-running yields the same final state.
-- ============================================================================

BEGIN;

-- ── Table ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.oauth_states (
    state         TEXT        PRIMARY KEY,
    user_id       UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    provider      TEXT        NOT NULL,
    redirect_uri  TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at    TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '10 minutes')
);

CREATE INDEX IF NOT EXISTS idx_oauth_states_expires
    ON public.oauth_states (expires_at);

CREATE INDEX IF NOT EXISTS idx_oauth_states_user_provider
    ON public.oauth_states (user_id, provider);

-- ── RLS ─────────────────────────────────────────────────────────────────────
ALTER TABLE public.oauth_states ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'oauth_states'
          AND policyname = 'oauth_states_service_role_all'
    ) THEN
        CREATE POLICY "oauth_states_service_role_all"
            ON public.oauth_states
            FOR ALL TO service_role
            USING (true) WITH CHECK (true);
    END IF;
END $$;

-- ── Cleanup helper ──────────────────────────────────────────────────────────
-- A periodic worker (or pg_cron) should call this to purge expired rows.
-- Safe to run anytime; no-op if nothing is expired.
CREATE OR REPLACE FUNCTION public.oauth_states_purge_expired()
RETURNS BIGINT
LANGUAGE sql
AS $$
    WITH deleted AS (
        DELETE FROM public.oauth_states
         WHERE expires_at < now()
         RETURNING 1
    )
    SELECT COUNT(*)::BIGINT FROM deleted;
$$;

COMMIT;
