-- ISSUE-012: durable recovery window and operational evidence for object GC.

CREATE TABLE IF NOT EXISTS public.version_object_gc_candidates (
    project_id text NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    object_id text NOT NULL CHECK (object_id ~ '^[0-9a-f]{40}$'),
    first_seen_at timestamptz NOT NULL,
    last_seen_at timestamptz NOT NULL,
    PRIMARY KEY (project_id, object_id)
);

CREATE INDEX IF NOT EXISTS idx_version_object_gc_candidates_maturity
    ON public.version_object_gc_candidates(project_id, first_seen_at);

CREATE TABLE IF NOT EXISTS public.version_object_gc_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id text NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    dry_run boolean NOT NULL,
    total_objects bigint NOT NULL DEFAULT 0,
    reachable_objects bigint NOT NULL DEFAULT 0,
    unreachable_objects bigint NOT NULL DEFAULT 0,
    eligible_objects bigint NOT NULL DEFAULT 0,
    quarantined_objects bigint NOT NULL DEFAULT 0,
    deleted_objects bigint NOT NULL DEFAULT 0,
    unreachable_bytes bigint NOT NULL DEFAULT 0,
    eligible_bytes bigint NOT NULL DEFAULT 0,
    deleted_bytes bigint NOT NULL DEFAULT 0,
    sweep_skipped_for_safety boolean NOT NULL DEFAULT false,
    errors jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_version_object_gc_runs_project_created
    ON public.version_object_gc_runs(project_id, created_at DESC);

ALTER TABLE public.version_object_gc_candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.version_object_gc_runs ENABLE ROW LEVEL SECURITY;

CREATE POLICY version_object_gc_candidates_service_role
    ON public.version_object_gc_candidates
    FOR ALL TO service_role USING (true) WITH CHECK (true);
CREATE POLICY version_object_gc_runs_service_role
    ON public.version_object_gc_runs
    FOR ALL TO service_role USING (true) WITH CHECK (true);

REVOKE ALL ON public.version_object_gc_candidates
    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.version_object_gc_runs
    FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.sync_version_object_gc_candidates(
    p_project_id text,
    p_object_ids text[],
    p_now timestamptz,
    p_quarantine_seconds integer
) RETURNS TABLE(object_id text)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    IF p_quarantine_seconds < 0 THEN
        RAISE EXCEPTION 'p_quarantine_seconds must be non-negative';
    END IF;

    DELETE FROM public.version_object_gc_candidates c
    WHERE c.project_id = p_project_id
      AND NOT (c.object_id = ANY(COALESCE(p_object_ids, ARRAY[]::text[])));

    INSERT INTO public.version_object_gc_candidates (
        project_id, object_id, first_seen_at, last_seen_at
    )
    SELECT p_project_id, candidate, p_now, p_now
    FROM unnest(COALESCE(p_object_ids, ARRAY[]::text[])) candidate
    ON CONFLICT (project_id, object_id) DO UPDATE
    SET last_seen_at = EXCLUDED.last_seen_at;

    RETURN QUERY
    SELECT c.object_id
    FROM public.version_object_gc_candidates c
    WHERE c.project_id = p_project_id
      AND c.object_id = ANY(COALESCE(p_object_ids, ARRAY[]::text[]))
      AND c.first_seen_at <= p_now - make_interval(secs => p_quarantine_seconds);
END;
$$;

REVOKE ALL ON FUNCTION public.sync_version_object_gc_candidates(
    text, text[], timestamptz, integer
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.sync_version_object_gc_candidates(
    text, text[], timestamptz, integer
) TO service_role;
